name: Main Branch Merge

on:
  push:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: lint
    secrets:
      SPOR_VM_SSH_KEY: ${{ secrets.SPOR_VM_SSH_KEY }}
      SPOR_VM_USER: ${{ secrets.SPOR_VM_USER }}
      SPOR_VM_IP: ${{ secrets.SPOR_VM_IP }}
